### ISSUE TITLE
Account suspended after only one course downloaded

### ISSUE THREAD

**Issue by pedrosimao** [kyoz/fem-downloader#1]
I get my account block and the following message:

> Hi Pedro,
> 
> Your account has been suspended for scripting or otherwise initiating downloads against our web player APIs. We'd appreciate it if you would halt your script or disable any browser plugin responsible for the activity. Offline viewing is available through our iOS and Android apps.If you have any questions, please review our Terms of Service.
> 
> You'll need to respond in the affirmative before your account will be restored.

**Comment by kyoz** [comment]
Hi @pedrosimao . I'm really sorry fot that. It's been a few years since i write this. I'm no longer watch video on Frontend Master website but i think they have updated their policy since they release these app that help you can watch offine on mobile device.

This is kind of easily to understand that they want to keep there content & properties...

I think there is some way to automate download their content without their tracking but for now i'v no time to looking on it.

Btw. I'm really sorry for this.
